version: 2.1

executors:
  ruby-executor:
    docker:
      - image: circleci/ruby:3.2.2-node
    working_directory: ~/app

jobs:
  test:
    executor: ruby-executor
    steps:
      - checkout
      - run: gem install bundler
      - run: bundle install --jobs=4 --retry=3
      - run: bundle exec rails db:create db:schema:load RAILS_ENV=test
      - run: bundle exec rspec

workflows:
  version: 2
  test:
    jobs:
      - test
